# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
            ],
            options={
                'ordering': ('-period_end',),
                'get_latest_by': 'period_end',
            },
        ),
        migrations.CreateModel(
            name='BillGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('rate_per_device', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('period', models.CharField(choices=[('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('YEARLY', 'yearly')], max_length=20)),
                ('active_from_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BilledOrganization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('organizations.organization',),
        ),
        migrations.AddField(
            model_name='billgenerator',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billed_by', to='organizations.Organization'),
        ),
    ]
