# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zc_billing', '0001_initial'),
        migrations.swappable_dependency(settings.ZCONNECT_DEVICE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='devices',
            field=models.ManyToManyField(to=settings.ZCONNECT_DEVICE_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='zc_billing.BillGenerator'),
        ),
    ]
