# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zconnect', '0002_create_other_models'),
        migrations.swappable_dependency(settings.ZCONNECT_DEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.FloatField(default=120.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.ZCONNECT_DEVICE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_name', models.CharField(blank=True, max_length=50)),
                ('descriptive_name', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('graph_type', models.CharField(choices=[('ts_bar', 'Bar graph'), ('ts_graph', 'Line graph')], default='ts_graph', max_length=20)),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum values over the aggregation period'), ('mean', 'Mean of values over the aggregation period'), ('median', 'Median of values over the aggregation period'), ('min', 'Minimum value over the aggregation period'), ('max', 'Maximum value over the aggregation period')], default='sum', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='zconnect.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='zc_timeseries.DeviceSensor')),
            ],
            options={
                'ordering': ('-ts',),
                'get_latest_by': 'ts',
            },
        ),
        migrations.AddField(
            model_name='devicesensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zc_timeseries.SensorType'),
        ),
        migrations.AddIndex(
            model_name='timeseriesdata',
            index=models.Index(fields=['sensor', '-ts'], name='ts_and_sensor_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdata',
            unique_together=set([('ts', 'sensor')]),
        ),
        migrations.AlterUniqueTogether(
            name='devicesensor',
            unique_together=set([('device', 'sensor_type')]),
        ),
    ]
