# Generated by Django 2.0.5 on 2018-05-31 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zc_timeseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesDataArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('aggregation_type', models.CharField(choices=[('sum', 'Sum values over the aggregation period'), ('mean', 'Mean of values over the aggregation period'), ('median', 'Median of values over the aggregation period'), ('min', 'Minimum value over the aggregation period'), ('max', 'Maximum value over the aggregation period')], max_length=20)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_data', to='zc_timeseries.DeviceSensor')),
            ],
            options={
                'ordering': ('-end',),
                'get_latest_by': 'end',
            },
        ),
        migrations.AddIndex(
            model_name='timeseriesdataarchive',
            index=models.Index(fields=['sensor', '-end'], name='end_and_sensor_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseriesdataarchive',
            unique_together={('start', 'end', 'sensor', 'aggregation_type')},
        ),
    ]
