# Generated by Django 2.0.5 on 2018-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0010_remove_timelineentry'),
        ('zc_timeseries', '0002_add_ts_archive'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensortype',
            unique_together={('sensor_name', 'product')},
        ),
    ]
