# Generated by Django 2.0.5 on 2018-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0008_org_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdefinition',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
