# Generated by Django 2.0.5 on 2018-05-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0009_event_defs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineentry',
            name='event',
        ),
        migrations.DeleteModel(
            name='TimelineEntry',
        ),
    ]
