# Generated by Django 2.0.5 on 2018-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zconnect', '0010_remove_timelineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfirmware',
            name='download_url',
            field=models.CharField(max_length=200),
        ),
    ]
