# Generated by Django 2.0.5 on 2018-06-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.ZCONNECT_DEVICE_MODEL),
        ('zconnect', '0011_fix_url_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('reported', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ZCONNECT_DEVICE_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='state_serializer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='devicestate',
            unique_together={('version', 'device')},
        ),
    ]
