# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zconnect._models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_model_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZCTestDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('fw_version', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['product'],
                'default_permissions': ['view', 'change', 'add', 'delete'],
            },
            bases=(zconnect._models.mixins.EventDefinitionMixin, models.Model),
        ),
    ]

